apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: faculty-management
data:
  PORT: "5000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "faculty_db"
  JWT_SECRET: "faculty_management_secret_key_2024"
